FROM python:3.9.2-slim-buster
WORKDIR /usr/src/app
COPY ./requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY ./script/cron.py ./
COPY ./script/main.py ./
CMD ["python", "./cron.py"]